# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crayfish_viewer_vector_options_dialog_widget.ui'
#
# Created: Thu Apr 23 16:27:14 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(652, 351)
        self.gridLayout_9 = QtGui.QGridLayout(Dialog)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.generalOptionsGroupBox = QtGui.QGroupBox(Dialog)
        self.generalOptionsGroupBox.setObjectName(_fromUtf8("generalOptionsGroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.generalOptionsGroupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.shaftLengthLabel = QtGui.QLabel(self.generalOptionsGroupBox)
        self.shaftLengthLabel.setObjectName(_fromUtf8("shaftLengthLabel"))
        self.horizontalLayout_2.addWidget(self.shaftLengthLabel)
        self.shaftLengthComboBox = QtGui.QComboBox(self.generalOptionsGroupBox)
        self.shaftLengthComboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.shaftLengthComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.shaftLengthComboBox.setObjectName(_fromUtf8("shaftLengthComboBox"))
        self.shaftLengthComboBox.addItem(_fromUtf8(""))
        self.shaftLengthComboBox.addItem(_fromUtf8(""))
        self.shaftLengthComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.shaftLengthComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.stackedWidget = QtGui.QStackedWidget(self.generalOptionsGroupBox)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_6 = QtGui.QGridLayout(self.page)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.maximumShaftLineEdit = QtGui.QLineEdit(self.page)
        self.maximumShaftLineEdit.setObjectName(_fromUtf8("maximumShaftLineEdit"))
        self.gridLayout_6.addWidget(self.maximumShaftLineEdit, 1, 1, 1, 1)
        self.minimumShaftLineEdit = QtGui.QLineEdit(self.page)
        self.minimumShaftLineEdit.setObjectName(_fromUtf8("minimumShaftLineEdit"))
        self.gridLayout_6.addWidget(self.minimumShaftLineEdit, 0, 1, 1, 1)
        self.maximumShaftLabel = QtGui.QLabel(self.page)
        self.maximumShaftLabel.setObjectName(_fromUtf8("maximumShaftLabel"))
        self.gridLayout_6.addWidget(self.maximumShaftLabel, 1, 0, 1, 1)
        self.minimumShaftLabel = QtGui.QLabel(self.page)
        self.minimumShaftLabel.setObjectName(_fromUtf8("minimumShaftLabel"))
        self.gridLayout_6.addWidget(self.minimumShaftLabel, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.scaleByFactorOfLabel = QtGui.QLabel(self.page_2)
        self.scaleByFactorOfLabel.setObjectName(_fromUtf8("scaleByFactorOfLabel"))
        self.gridLayout_7.addWidget(self.scaleByFactorOfLabel, 0, 0, 1, 1)
        self.scaleByFactorOfLineEdit = QtGui.QLineEdit(self.page_2)
        self.scaleByFactorOfLineEdit.setObjectName(_fromUtf8("scaleByFactorOfLineEdit"))
        self.gridLayout_7.addWidget(self.scaleByFactorOfLineEdit, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.LengthLabel = QtGui.QLabel(self.page_3)
        self.LengthLabel.setObjectName(_fromUtf8("LengthLabel"))
        self.gridLayout_8.addWidget(self.LengthLabel, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 1, 1, 1, 1)
        self.lengthLineEdit = QtGui.QLineEdit(self.page_3)
        self.lengthLineEdit.setObjectName(_fromUtf8("lengthLineEdit"))
        self.gridLayout_8.addWidget(self.lengthLineEdit, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineWidthLabel = QtGui.QLabel(self.generalOptionsGroupBox)
        self.lineWidthLabel.setObjectName(_fromUtf8("lineWidthLabel"))
        self.horizontalLayout.addWidget(self.lineWidthLabel)
        self.lineWidthSpinBox = QtGui.QSpinBox(self.generalOptionsGroupBox)
        self.lineWidthSpinBox.setMinimum(1)
        self.lineWidthSpinBox.setMaximum(10)
        self.lineWidthSpinBox.setObjectName(_fromUtf8("lineWidthSpinBox"))
        self.horizontalLayout.addWidget(self.lineWidthSpinBox)
        self.pxLabel = QtGui.QLabel(self.generalOptionsGroupBox)
        self.pxLabel.setObjectName(_fromUtf8("pxLabel"))
        self.horizontalLayout.addWidget(self.pxLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.displayVectorsOnGridGroupBox = QtGui.QGroupBox(self.generalOptionsGroupBox)
        self.displayVectorsOnGridGroupBox.setCheckable(True)
        self.displayVectorsOnGridGroupBox.setChecked(False)
        self.displayVectorsOnGridGroupBox.setObjectName(_fromUtf8("displayVectorsOnGridGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.displayVectorsOnGridGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.xSpacingLabel = QtGui.QLabel(self.displayVectorsOnGridGroupBox)
        self.xSpacingLabel.setObjectName(_fromUtf8("xSpacingLabel"))
        self.gridLayout.addWidget(self.xSpacingLabel, 0, 0, 1, 1)
        self.xSpacingLineEdit = QtGui.QLineEdit(self.displayVectorsOnGridGroupBox)
        self.xSpacingLineEdit.setObjectName(_fromUtf8("xSpacingLineEdit"))
        self.gridLayout.addWidget(self.xSpacingLineEdit, 0, 1, 1, 1)
        self.pxLabel_2 = QtGui.QLabel(self.displayVectorsOnGridGroupBox)
        self.pxLabel_2.setObjectName(_fromUtf8("pxLabel_2"))
        self.gridLayout.addWidget(self.pxLabel_2, 0, 2, 1, 1)
        self.ySpacingLabel = QtGui.QLabel(self.displayVectorsOnGridGroupBox)
        self.ySpacingLabel.setObjectName(_fromUtf8("ySpacingLabel"))
        self.gridLayout.addWidget(self.ySpacingLabel, 1, 0, 1, 1)
        self.ySpacingLineEdit = QtGui.QLineEdit(self.displayVectorsOnGridGroupBox)
        self.ySpacingLineEdit.setObjectName(_fromUtf8("ySpacingLineEdit"))
        self.gridLayout.addWidget(self.ySpacingLineEdit, 1, 1, 1, 1)
        self.pxLabel_3 = QtGui.QLabel(self.displayVectorsOnGridGroupBox)
        self.pxLabel_3.setObjectName(_fromUtf8("pxLabel_3"))
        self.gridLayout.addWidget(self.pxLabel_3, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.displayVectorsOnGridGroupBox)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.generalOptionsGroupBox)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.headOptionsGroupBox = QtGui.QGroupBox(Dialog)
        self.headOptionsGroupBox.setObjectName(_fromUtf8("headOptionsGroupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.headOptionsGroupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.headWidthLabel = QtGui.QLabel(self.headOptionsGroupBox)
        self.headWidthLabel.setObjectName(_fromUtf8("headWidthLabel"))
        self.gridLayout_4.addWidget(self.headWidthLabel, 0, 0, 1, 1)
        self.headWidthLineEdit = QtGui.QLineEdit(self.headOptionsGroupBox)
        self.headWidthLineEdit.setObjectName(_fromUtf8("headWidthLineEdit"))
        self.gridLayout_4.addWidget(self.headWidthLineEdit, 0, 1, 1, 1)
        self.percShaftLenLabel = QtGui.QLabel(self.headOptionsGroupBox)
        self.percShaftLenLabel.setObjectName(_fromUtf8("percShaftLenLabel"))
        self.gridLayout_4.addWidget(self.percShaftLenLabel, 0, 2, 1, 1)
        self.headLengthLabel = QtGui.QLabel(self.headOptionsGroupBox)
        self.headLengthLabel.setObjectName(_fromUtf8("headLengthLabel"))
        self.gridLayout_4.addWidget(self.headLengthLabel, 1, 0, 1, 1)
        self.headLengthLineEdit = QtGui.QLineEdit(self.headOptionsGroupBox)
        self.headLengthLineEdit.setObjectName(_fromUtf8("headLengthLineEdit"))
        self.gridLayout_4.addWidget(self.headLengthLineEdit, 1, 1, 1, 1)
        self.percShaftLenLabel_2 = QtGui.QLabel(self.headOptionsGroupBox)
        self.percShaftLenLabel_2.setObjectName(_fromUtf8("percShaftLenLabel_2"))
        self.gridLayout_4.addWidget(self.percShaftLenLabel_2, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.headOptionsGroupBox)
        self.filterByMagGroupBox = QtGui.QGroupBox(Dialog)
        self.filterByMagGroupBox.setEnabled(False)
        self.filterByMagGroupBox.setCheckable(True)
        self.filterByMagGroupBox.setChecked(False)
        self.filterByMagGroupBox.setObjectName(_fromUtf8("filterByMagGroupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.filterByMagGroupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.maximumMagLineEdit = QtGui.QLineEdit(self.filterByMagGroupBox)
        self.maximumMagLineEdit.setObjectName(_fromUtf8("maximumMagLineEdit"))
        self.gridLayout_5.addWidget(self.maximumMagLineEdit, 1, 1, 1, 1)
        self.minimumMagLabel = QtGui.QLabel(self.filterByMagGroupBox)
        self.minimumMagLabel.setObjectName(_fromUtf8("minimumMagLabel"))
        self.gridLayout_5.addWidget(self.minimumMagLabel, 0, 0, 1, 1)
        self.minimumMagLineEdit = QtGui.QLineEdit(self.filterByMagGroupBox)
        self.minimumMagLineEdit.setObjectName(_fromUtf8("minimumMagLineEdit"))
        self.gridLayout_5.addWidget(self.minimumMagLineEdit, 0, 1, 1, 1)
        self.maximumMagLabel = QtGui.QLabel(self.filterByMagGroupBox)
        self.maximumMagLabel.setObjectName(_fromUtf8("maximumMagLabel"))
        self.gridLayout_5.addWidget(self.maximumMagLabel, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.filterByMagGroupBox)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.gridLayout_9.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.shaftLengthComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.shaftLengthMethodChanged)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.shaftLengthComboBox, self.minimumShaftLineEdit)
        Dialog.setTabOrder(self.minimumShaftLineEdit, self.maximumShaftLineEdit)
        Dialog.setTabOrder(self.maximumShaftLineEdit, self.scaleByFactorOfLineEdit)
        Dialog.setTabOrder(self.scaleByFactorOfLineEdit, self.lengthLineEdit)
        Dialog.setTabOrder(self.lengthLineEdit, self.lineWidthSpinBox)
        Dialog.setTabOrder(self.lineWidthSpinBox, self.displayVectorsOnGridGroupBox)
        Dialog.setTabOrder(self.displayVectorsOnGridGroupBox, self.xSpacingLineEdit)
        Dialog.setTabOrder(self.xSpacingLineEdit, self.ySpacingLineEdit)
        Dialog.setTabOrder(self.ySpacingLineEdit, self.headWidthLineEdit)
        Dialog.setTabOrder(self.headWidthLineEdit, self.headLengthLineEdit)
        Dialog.setTabOrder(self.headLengthLineEdit, self.filterByMagGroupBox)
        Dialog.setTabOrder(self.filterByMagGroupBox, self.minimumMagLineEdit)
        Dialog.setTabOrder(self.minimumMagLineEdit, self.maximumMagLineEdit)
        Dialog.setTabOrder(self.maximumMagLineEdit, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Vector Rendering Options", None))
        self.generalOptionsGroupBox.setTitle(_translate("Dialog", "General Options", None))
        self.shaftLengthLabel.setText(_translate("Dialog", "Shaft Length", None))
        self.shaftLengthComboBox.setItemText(0, _translate("Dialog", "Defined by Min and Max", None))
        self.shaftLengthComboBox.setItemText(1, _translate("Dialog", "Scaled to Magnitude", None))
        self.shaftLengthComboBox.setItemText(2, _translate("Dialog", "Fixed", None))
        self.maximumShaftLabel.setText(_translate("Dialog", "Maximum", None))
        self.minimumShaftLabel.setText(_translate("Dialog", "Minimum", None))
        self.scaleByFactorOfLabel.setText(_translate("Dialog", "Scale by a Factor of:", None))
        self.LengthLabel.setText(_translate("Dialog", "Length", None))
        self.lineWidthLabel.setText(_translate("Dialog", "Line Width", None))
        self.pxLabel.setText(_translate("Dialog", "px", None))
        self.displayVectorsOnGridGroupBox.setTitle(_translate("Dialog", "Display Vectors on User Grid", None))
        self.xSpacingLabel.setText(_translate("Dialog", "X Spacing", None))
        self.pxLabel_2.setText(_translate("Dialog", "px", None))
        self.ySpacingLabel.setText(_translate("Dialog", "Y Spacing", None))
        self.pxLabel_3.setText(_translate("Dialog", "px", None))
        self.headOptionsGroupBox.setTitle(_translate("Dialog", "Head Options", None))
        self.headWidthLabel.setText(_translate("Dialog", "Width", None))
        self.percShaftLenLabel.setText(_translate("Dialog", "% of Shaft Length", None))
        self.headLengthLabel.setText(_translate("Dialog", "Length", None))
        self.percShaftLenLabel_2.setText(_translate("Dialog", "% of Shaft Length", None))
        self.filterByMagGroupBox.setTitle(_translate("Dialog", "Filter by Magnitude", None))
        self.minimumMagLabel.setText(_translate("Dialog", "Minimum", None))
        self.maximumMagLabel.setText(_translate("Dialog", "Maximum", None))

