# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plugin/crayfish_viewer_vector_options_dialog_widget.ui'
#
# Created: Tue Mar 15 14:38:42 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(341, 555)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.lineWidthLabel = QtGui.QLabel(Dialog)
        self.lineWidthLabel.setObjectName(_fromUtf8("lineWidthLabel"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.lineWidthLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineWidthSpinBox = QtGui.QSpinBox(Dialog)
        self.lineWidthSpinBox.setMinimum(1)
        self.lineWidthSpinBox.setMaximum(10000)
        self.lineWidthSpinBox.setObjectName(_fromUtf8("lineWidthSpinBox"))
        self.horizontalLayout.addWidget(self.lineWidthSpinBox)
        self.pxLabel = QtGui.QLabel(Dialog)
        self.pxLabel.setObjectName(_fromUtf8("pxLabel"))
        self.horizontalLayout.addWidget(self.pxLabel)
        self.formLayout_4.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.colorButton = QgsColorButton(Dialog)
        self.colorButton.setObjectName(_fromUtf8("colorButton"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.colorButton)
        self.verticalLayout.addLayout(self.formLayout_4)
        self.generalOptionsGroupBox = QtGui.QGroupBox(Dialog)
        self.generalOptionsGroupBox.setObjectName(_fromUtf8("generalOptionsGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.generalOptionsGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.shaftLengthComboBox = QtGui.QComboBox(self.generalOptionsGroupBox)
        self.shaftLengthComboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.shaftLengthComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.shaftLengthComboBox.setObjectName(_fromUtf8("shaftLengthComboBox"))
        self.shaftLengthComboBox.addItem(_fromUtf8(""))
        self.shaftLengthComboBox.addItem(_fromUtf8(""))
        self.shaftLengthComboBox.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.shaftLengthComboBox)
        self.stackedWidget = QtGui.QStackedWidget(self.generalOptionsGroupBox)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.formLayout = QtGui.QFormLayout(self.page)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.minimumShaftLabel = QtGui.QLabel(self.page)
        self.minimumShaftLabel.setObjectName(_fromUtf8("minimumShaftLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.minimumShaftLabel)
        self.minimumShaftLineEdit = QtGui.QLineEdit(self.page)
        self.minimumShaftLineEdit.setObjectName(_fromUtf8("minimumShaftLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.minimumShaftLineEdit)
        self.maximumShaftLabel = QtGui.QLabel(self.page)
        self.maximumShaftLabel.setObjectName(_fromUtf8("maximumShaftLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.maximumShaftLabel)
        self.maximumShaftLineEdit = QtGui.QLineEdit(self.page)
        self.maximumShaftLineEdit.setObjectName(_fromUtf8("maximumShaftLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.maximumShaftLineEdit)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.page_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.scaleByFactorOfLabel = QtGui.QLabel(self.page_2)
        self.scaleByFactorOfLabel.setObjectName(_fromUtf8("scaleByFactorOfLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.scaleByFactorOfLabel)
        self.scaleByFactorOfLineEdit = QtGui.QLineEdit(self.page_2)
        self.scaleByFactorOfLineEdit.setObjectName(_fromUtf8("scaleByFactorOfLineEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.scaleByFactorOfLineEdit)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.page_3)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.LengthLabel = QtGui.QLabel(self.page_3)
        self.LengthLabel.setObjectName(_fromUtf8("LengthLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.LengthLabel)
        self.lengthLineEdit = QtGui.QLineEdit(self.page_3)
        self.lengthLineEdit.setObjectName(_fromUtf8("lengthLineEdit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lengthLineEdit)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.generalOptionsGroupBox)
        self.headOptionsGroupBox = QtGui.QGroupBox(Dialog)
        self.headOptionsGroupBox.setObjectName(_fromUtf8("headOptionsGroupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.headOptionsGroupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.headWidthLabel = QtGui.QLabel(self.headOptionsGroupBox)
        self.headWidthLabel.setObjectName(_fromUtf8("headWidthLabel"))
        self.gridLayout_4.addWidget(self.headWidthLabel, 0, 0, 1, 1)
        self.headWidthLineEdit = QtGui.QLineEdit(self.headOptionsGroupBox)
        self.headWidthLineEdit.setObjectName(_fromUtf8("headWidthLineEdit"))
        self.gridLayout_4.addWidget(self.headWidthLineEdit, 0, 1, 1, 1)
        self.percShaftLenLabel = QtGui.QLabel(self.headOptionsGroupBox)
        self.percShaftLenLabel.setObjectName(_fromUtf8("percShaftLenLabel"))
        self.gridLayout_4.addWidget(self.percShaftLenLabel, 0, 2, 1, 1)
        self.headLengthLabel = QtGui.QLabel(self.headOptionsGroupBox)
        self.headLengthLabel.setObjectName(_fromUtf8("headLengthLabel"))
        self.gridLayout_4.addWidget(self.headLengthLabel, 1, 0, 1, 1)
        self.headLengthLineEdit = QtGui.QLineEdit(self.headOptionsGroupBox)
        self.headLengthLineEdit.setObjectName(_fromUtf8("headLengthLineEdit"))
        self.gridLayout_4.addWidget(self.headLengthLineEdit, 1, 1, 1, 1)
        self.percShaftLenLabel_2 = QtGui.QLabel(self.headOptionsGroupBox)
        self.percShaftLenLabel_2.setObjectName(_fromUtf8("percShaftLenLabel_2"))
        self.gridLayout_4.addWidget(self.percShaftLenLabel_2, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.headOptionsGroupBox)
        self.filterByMagGroupBox = QtGui.QGroupBox(Dialog)
        self.filterByMagGroupBox.setChecked(False)
        self.filterByMagGroupBox.setObjectName(_fromUtf8("filterByMagGroupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.filterByMagGroupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.maxMagLineEdit = QtGui.QLineEdit(self.filterByMagGroupBox)
        self.maxMagLineEdit.setObjectName(_fromUtf8("maxMagLineEdit"))
        self.gridLayout_5.addWidget(self.maxMagLineEdit, 1, 1, 1, 1)
        self.minimumMagLabel = QtGui.QLabel(self.filterByMagGroupBox)
        self.minimumMagLabel.setObjectName(_fromUtf8("minimumMagLabel"))
        self.gridLayout_5.addWidget(self.minimumMagLabel, 0, 0, 1, 1)
        self.minMagLineEdit = QtGui.QLineEdit(self.filterByMagGroupBox)
        self.minMagLineEdit.setObjectName(_fromUtf8("minMagLineEdit"))
        self.gridLayout_5.addWidget(self.minMagLineEdit, 0, 1, 1, 1)
        self.maximumMagLabel = QtGui.QLabel(self.filterByMagGroupBox)
        self.maximumMagLabel.setObjectName(_fromUtf8("maximumMagLabel"))
        self.gridLayout_5.addWidget(self.maximumMagLabel, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.filterByMagGroupBox)
        self.displayVectorsOnGridGroupBox = QtGui.QGroupBox(Dialog)
        self.displayVectorsOnGridGroupBox.setCheckable(True)
        self.displayVectorsOnGridGroupBox.setChecked(False)
        self.displayVectorsOnGridGroupBox.setObjectName(_fromUtf8("displayVectorsOnGridGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.displayVectorsOnGridGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.xSpacingLabel = QtGui.QLabel(self.displayVectorsOnGridGroupBox)
        self.xSpacingLabel.setObjectName(_fromUtf8("xSpacingLabel"))
        self.gridLayout.addWidget(self.xSpacingLabel, 0, 0, 1, 1)
        self.xSpacingLineEdit = QtGui.QLineEdit(self.displayVectorsOnGridGroupBox)
        self.xSpacingLineEdit.setObjectName(_fromUtf8("xSpacingLineEdit"))
        self.gridLayout.addWidget(self.xSpacingLineEdit, 0, 1, 1, 1)
        self.pxLabel_2 = QtGui.QLabel(self.displayVectorsOnGridGroupBox)
        self.pxLabel_2.setObjectName(_fromUtf8("pxLabel_2"))
        self.gridLayout.addWidget(self.pxLabel_2, 0, 2, 1, 1)
        self.ySpacingLabel = QtGui.QLabel(self.displayVectorsOnGridGroupBox)
        self.ySpacingLabel.setObjectName(_fromUtf8("ySpacingLabel"))
        self.gridLayout.addWidget(self.ySpacingLabel, 1, 0, 1, 1)
        self.ySpacingLineEdit = QtGui.QLineEdit(self.displayVectorsOnGridGroupBox)
        self.ySpacingLineEdit.setObjectName(_fromUtf8("ySpacingLineEdit"))
        self.gridLayout.addWidget(self.ySpacingLineEdit, 1, 1, 1, 1)
        self.pxLabel_3 = QtGui.QLabel(self.displayVectorsOnGridGroupBox)
        self.pxLabel_3.setObjectName(_fromUtf8("pxLabel_3"))
        self.gridLayout.addWidget(self.pxLabel_3, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.displayVectorsOnGridGroupBox)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.shaftLengthComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.shaftLengthMethodChanged)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.minimumShaftLineEdit, self.maximumShaftLineEdit)
        Dialog.setTabOrder(self.maximumShaftLineEdit, self.scaleByFactorOfLineEdit)
        Dialog.setTabOrder(self.scaleByFactorOfLineEdit, self.lengthLineEdit)
        Dialog.setTabOrder(self.lengthLineEdit, self.lineWidthSpinBox)
        Dialog.setTabOrder(self.lineWidthSpinBox, self.xSpacingLineEdit)
        Dialog.setTabOrder(self.xSpacingLineEdit, self.ySpacingLineEdit)
        Dialog.setTabOrder(self.ySpacingLineEdit, self.headWidthLineEdit)
        Dialog.setTabOrder(self.headWidthLineEdit, self.headLengthLineEdit)
        Dialog.setTabOrder(self.headLengthLineEdit, self.filterByMagGroupBox)
        Dialog.setTabOrder(self.filterByMagGroupBox, self.minMagLineEdit)
        Dialog.setTabOrder(self.minMagLineEdit, self.maxMagLineEdit)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Vector Rendering Options", None))
        self.lineWidthLabel.setText(_translate("Dialog", "Line Width", None))
        self.pxLabel.setText(_translate("Dialog", "px", None))
        self.label.setText(_translate("Dialog", "Color", None))
        self.generalOptionsGroupBox.setTitle(_translate("Dialog", "Arrow Length", None))
        self.shaftLengthComboBox.setItemText(0, _translate("Dialog", "Defined by Min and Max", None))
        self.shaftLengthComboBox.setItemText(1, _translate("Dialog", "Scaled to Magnitude", None))
        self.shaftLengthComboBox.setItemText(2, _translate("Dialog", "Fixed", None))
        self.minimumShaftLabel.setText(_translate("Dialog", "Minimum", None))
        self.maximumShaftLabel.setText(_translate("Dialog", "Maximum", None))
        self.scaleByFactorOfLabel.setText(_translate("Dialog", "Scale by a Factor of:", None))
        self.LengthLabel.setText(_translate("Dialog", "Length", None))
        self.headOptionsGroupBox.setTitle(_translate("Dialog", "Head Options", None))
        self.headWidthLabel.setText(_translate("Dialog", "Width", None))
        self.percShaftLenLabel.setText(_translate("Dialog", "% of Shaft Length", None))
        self.headLengthLabel.setText(_translate("Dialog", "Length", None))
        self.percShaftLenLabel_2.setText(_translate("Dialog", "% of Shaft Length", None))
        self.filterByMagGroupBox.setTitle(_translate("Dialog", "Filter by Magnitude", None))
        self.minimumMagLabel.setText(_translate("Dialog", "Minimum", None))
        self.maximumMagLabel.setText(_translate("Dialog", "Maximum", None))
        self.displayVectorsOnGridGroupBox.setTitle(_translate("Dialog", "Display Vectors on User Grid", None))
        self.xSpacingLabel.setText(_translate("Dialog", "X Spacing", None))
        self.pxLabel_2.setText(_translate("Dialog", "px", None))
        self.ySpacingLabel.setText(_translate("Dialog", "Y Spacing", None))
        self.pxLabel_3.setText(_translate("Dialog", "px", None))

from qgis.gui import QgsColorButton
