# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'illuvis/upload_dialog_widget.ui'
#
# Created: Wed Nov 12 11:26:54 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(458, 470)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/illuvis/illuvis_u_32w.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.diskUsageLabel = QtGui.QLabel(Dialog)
        self.diskUsageLabel.setObjectName(_fromUtf8("diskUsageLabel"))
        self.horizontalLayout_3.addWidget(self.diskUsageLabel)
        self.diskUseProgressBar = QtGui.QProgressBar(Dialog)
        self.diskUseProgressBar.setMinimum(0)
        self.diskUseProgressBar.setMaximum(500)
        self.diskUseProgressBar.setProperty("value", 0)
        self.diskUseProgressBar.setTextVisible(True)
        self.diskUseProgressBar.setObjectName(_fromUtf8("diskUseProgressBar"))
        self.horizontalLayout_3.addWidget(self.diskUseProgressBar)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.connectedAsLabel = QtGui.QLabel(Dialog)
        self.connectedAsLabel.setObjectName(_fromUtf8("connectedAsLabel"))
        self.gridLayout.addWidget(self.connectedAsLabel, 1, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        self.connectionSettingsPushButton = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectionSettingsPushButton.sizePolicy().hasHeightForWidth())
        self.connectionSettingsPushButton.setSizePolicy(sizePolicy)
        self.connectionSettingsPushButton.setObjectName(_fromUtf8("connectionSettingsPushButton"))
        self.gridLayout.addWidget(self.connectionSettingsPushButton, 2, 0, 1, 1)
        self.iconLabel = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconLabel.sizePolicy().hasHeightForWidth())
        self.iconLabel.setSizePolicy(sizePolicy)
        self.iconLabel.setText(_fromUtf8(""))
        self.iconLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/illuvis/illuvis_logo_150w.png")))
        self.iconLabel.setScaledContents(False)
        self.iconLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.iconLabel.setObjectName(_fromUtf8("iconLabel"))
        self.gridLayout.addWidget(self.iconLabel, 1, 2, 3, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.projectLabel = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectLabel.sizePolicy().hasHeightForWidth())
        self.projectLabel.setSizePolicy(sizePolicy)
        self.projectLabel.setObjectName(_fromUtf8("projectLabel"))
        self.horizontalLayout.addWidget(self.projectLabel)
        self.projectComboBox = QtGui.QComboBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectComboBox.sizePolicy().hasHeightForWidth())
        self.projectComboBox.setSizePolicy(sizePolicy)
        self.projectComboBox.setObjectName(_fromUtf8("projectComboBox"))
        self.horizontalLayout.addWidget(self.projectComboBox)
        self.deleteProjectPushButton = QtGui.QPushButton(Dialog)
        self.deleteProjectPushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteProjectPushButton.sizePolicy().hasHeightForWidth())
        self.deleteProjectPushButton.setSizePolicy(sizePolicy)
        self.deleteProjectPushButton.setObjectName(_fromUtf8("deleteProjectPushButton"))
        self.horizontalLayout.addWidget(self.deleteProjectPushButton)
        self.newProjectPushButton = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newProjectPushButton.sizePolicy().hasHeightForWidth())
        self.newProjectPushButton.setSizePolicy(sizePolicy)
        self.newProjectPushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.newProjectPushButton.setObjectName(_fromUtf8("newProjectPushButton"))
        self.horizontalLayout.addWidget(self.newProjectPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.deleteScenarioPushButton = QtGui.QPushButton(self.tab)
        self.deleteScenarioPushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteScenarioPushButton.sizePolicy().hasHeightForWidth())
        self.deleteScenarioPushButton.setSizePolicy(sizePolicy)
        self.deleteScenarioPushButton.setObjectName(_fromUtf8("deleteScenarioPushButton"))
        self.gridLayout_2.addWidget(self.deleteScenarioPushButton, 0, 2, 1, 1)
        self.eventLabel = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventLabel.sizePolicy().hasHeightForWidth())
        self.eventLabel.setSizePolicy(sizePolicy)
        self.eventLabel.setObjectName(_fromUtf8("eventLabel"))
        self.gridLayout_2.addWidget(self.eventLabel, 1, 0, 1, 1)
        self.resultFileLineEdit = QtGui.QLineEdit(self.tab)
        self.resultFileLineEdit.setObjectName(_fromUtf8("resultFileLineEdit"))
        self.gridLayout_2.addWidget(self.resultFileLineEdit, 10, 1, 1, 2)
        self.resultTypeLabel = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultTypeLabel.sizePolicy().hasHeightForWidth())
        self.resultTypeLabel.setSizePolicy(sizePolicy)
        self.resultTypeLabel.setObjectName(_fromUtf8("resultTypeLabel"))
        self.gridLayout_2.addWidget(self.resultTypeLabel, 5, 0, 1, 1)
        self.eventComboBox = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventComboBox.sizePolicy().hasHeightForWidth())
        self.eventComboBox.setSizePolicy(sizePolicy)
        self.eventComboBox.setObjectName(_fromUtf8("eventComboBox"))
        self.gridLayout_2.addWidget(self.eventComboBox, 1, 1, 1, 1)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 4)
        self.scenarioLabel = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scenarioLabel.sizePolicy().hasHeightForWidth())
        self.scenarioLabel.setSizePolicy(sizePolicy)
        self.scenarioLabel.setObjectName(_fromUtf8("scenarioLabel"))
        self.gridLayout_2.addWidget(self.scenarioLabel, 0, 0, 1, 1)
        self.uploadPushButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadPushButton.sizePolicy().hasHeightForWidth())
        self.uploadPushButton.setSizePolicy(sizePolicy)
        self.uploadPushButton.setObjectName(_fromUtf8("uploadPushButton"))
        self.gridLayout_2.addWidget(self.uploadPushButton, 13, 3, 1, 1)
        self.newEventPushButton = QtGui.QPushButton(self.tab)
        self.newEventPushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newEventPushButton.sizePolicy().hasHeightForWidth())
        self.newEventPushButton.setSizePolicy(sizePolicy)
        self.newEventPushButton.setObjectName(_fromUtf8("newEventPushButton"))
        self.gridLayout_2.addWidget(self.newEventPushButton, 1, 3, 1, 1)
        self.scenarioComboBox = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scenarioComboBox.sizePolicy().hasHeightForWidth())
        self.scenarioComboBox.setSizePolicy(sizePolicy)
        self.scenarioComboBox.setObjectName(_fromUtf8("scenarioComboBox"))
        self.gridLayout_2.addWidget(self.scenarioComboBox, 0, 1, 1, 1)
        self.newScenarioPushButton = QtGui.QPushButton(self.tab)
        self.newScenarioPushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newScenarioPushButton.sizePolicy().hasHeightForWidth())
        self.newScenarioPushButton.setSizePolicy(sizePolicy)
        self.newScenarioPushButton.setObjectName(_fromUtf8("newScenarioPushButton"))
        self.gridLayout_2.addWidget(self.newScenarioPushButton, 0, 3, 1, 1)
        self.deleteEventPushButton = QtGui.QPushButton(self.tab)
        self.deleteEventPushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteEventPushButton.sizePolicy().hasHeightForWidth())
        self.deleteEventPushButton.setSizePolicy(sizePolicy)
        self.deleteEventPushButton.setObjectName(_fromUtf8("deleteEventPushButton"))
        self.gridLayout_2.addWidget(self.deleteEventPushButton, 1, 2, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.tab)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_2.addWidget(self.progressBar, 13, 0, 1, 3)
        self.browsePushButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browsePushButton.sizePolicy().hasHeightForWidth())
        self.browsePushButton.setSizePolicy(sizePolicy)
        self.browsePushButton.setObjectName(_fromUtf8("browsePushButton"))
        self.gridLayout_2.addWidget(self.browsePushButton, 10, 3, 1, 1)
        self.fromFileRadioButton = QtGui.QRadioButton(self.tab)
        self.fromFileRadioButton.setObjectName(_fromUtf8("fromFileRadioButton"))
        self.gridLayout_2.addWidget(self.fromFileRadioButton, 10, 0, 1, 1)
        self.resultTypeComboBox = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultTypeComboBox.sizePolicy().hasHeightForWidth())
        self.resultTypeComboBox.setSizePolicy(sizePolicy)
        self.resultTypeComboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.resultTypeComboBox.setObjectName(_fromUtf8("resultTypeComboBox"))
        self.gridLayout_2.addWidget(self.resultTypeComboBox, 5, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 8, 0, 1, 1)
        self.resolutionSpinBox = QtGui.QDoubleSpinBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resolutionSpinBox.sizePolicy().hasHeightForWidth())
        self.resolutionSpinBox.setSizePolicy(sizePolicy)
        self.resolutionSpinBox.setMaximum(9999.99)
        self.resolutionSpinBox.setProperty("value", 10.0)
        self.resolutionSpinBox.setObjectName(_fromUtf8("resolutionSpinBox"))
        self.gridLayout_2.addWidget(self.resolutionSpinBox, 8, 1, 1, 1)
        self.fromCurrentRadioButton = QtGui.QRadioButton(self.tab)
        self.fromCurrentRadioButton.setChecked(True)
        self.fromCurrentRadioButton.setObjectName(_fromUtf8("fromCurrentRadioButton"))
        self.gridLayout_2.addWidget(self.fromCurrentRadioButton, 7, 0, 1, 4)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.overlayComboBox = QtGui.QComboBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overlayComboBox.sizePolicy().hasHeightForWidth())
        self.overlayComboBox.setSizePolicy(sizePolicy)
        self.overlayComboBox.setObjectName(_fromUtf8("overlayComboBox"))
        self.horizontalLayout_2.addWidget(self.overlayComboBox)
        self.deleteOverlayPushButton = QtGui.QPushButton(self.tab_2)
        self.deleteOverlayPushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteOverlayPushButton.sizePolicy().hasHeightForWidth())
        self.deleteOverlayPushButton.setSizePolicy(sizePolicy)
        self.deleteOverlayPushButton.setObjectName(_fromUtf8("deleteOverlayPushButton"))
        self.horizontalLayout_2.addWidget(self.deleteOverlayPushButton)
        self.newOverlayPushButton = QtGui.QPushButton(self.tab_2)
        self.newOverlayPushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newOverlayPushButton.sizePolicy().hasHeightForWidth())
        self.newOverlayPushButton.setSizePolicy(sizePolicy)
        self.newOverlayPushButton.setObjectName(_fromUtf8("newOverlayPushButton"))
        self.horizontalLayout_2.addWidget(self.newOverlayPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 200, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        spacerItem3 = QtGui.QSpacerItem(5, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.statusLabel = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.horizontalLayout_4.addWidget(self.statusLabel)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.uploadPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.accept)
        QtCore.QObject.connect(self.browsePushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.browseForFile)
        QtCore.QObject.connect(self.connectionSettingsPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.connectionSettingsButtonPressed)
        QtCore.QObject.connect(self.scenarioComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.refreshEvents)
        QtCore.QObject.connect(self.newProjectPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.newProjectPushButtonPressed)
        QtCore.QObject.connect(self.newScenarioPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.newScenarioPushButtonPressed)
        QtCore.QObject.connect(self.newEventPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.newEventPushButtonPressed)
        QtCore.QObject.connect(self.deleteProjectPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.deleteProjectPushButtonPressed)
        QtCore.QObject.connect(self.deleteScenarioPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.deleteScenarioPushButtonPressed)
        QtCore.QObject.connect(self.deleteEventPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.deleteEventPushButtonPressed)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("helpRequested()")), Dialog.helpPressed)
        QtCore.QObject.connect(self.newOverlayPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.newOverlayPushButtonPressed)
        QtCore.QObject.connect(self.projectComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.projectComboBoxChanged)
        QtCore.QObject.connect(self.deleteOverlayPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.deleteOverlayPushButtonPressed)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.connectionSettingsPushButton, self.projectComboBox)
        Dialog.setTabOrder(self.projectComboBox, self.deleteProjectPushButton)
        Dialog.setTabOrder(self.deleteProjectPushButton, self.newProjectPushButton)
        Dialog.setTabOrder(self.newProjectPushButton, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.scenarioComboBox)
        Dialog.setTabOrder(self.scenarioComboBox, self.deleteScenarioPushButton)
        Dialog.setTabOrder(self.deleteScenarioPushButton, self.newScenarioPushButton)
        Dialog.setTabOrder(self.newScenarioPushButton, self.eventComboBox)
        Dialog.setTabOrder(self.eventComboBox, self.deleteEventPushButton)
        Dialog.setTabOrder(self.deleteEventPushButton, self.newEventPushButton)
        Dialog.setTabOrder(self.newEventPushButton, self.resultTypeComboBox)
        Dialog.setTabOrder(self.resultTypeComboBox, self.fromCurrentRadioButton)
        Dialog.setTabOrder(self.fromCurrentRadioButton, self.resolutionSpinBox)
        Dialog.setTabOrder(self.resolutionSpinBox, self.fromFileRadioButton)
        Dialog.setTabOrder(self.fromFileRadioButton, self.resultFileLineEdit)
        Dialog.setTabOrder(self.resultFileLineEdit, self.browsePushButton)
        Dialog.setTabOrder(self.browsePushButton, self.uploadPushButton)
        Dialog.setTabOrder(self.uploadPushButton, self.overlayComboBox)
        Dialog.setTabOrder(self.overlayComboBox, self.deleteOverlayPushButton)
        Dialog.setTabOrder(self.deleteOverlayPushButton, self.newOverlayPushButton)
        Dialog.setTabOrder(self.newOverlayPushButton, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "illuvis Uploader", None))
        self.diskUsageLabel.setText(_translate("Dialog", "Disk Usage", None))
        self.diskUseProgressBar.setFormat(_translate("Dialog", "%v MB", None))
        self.connectedAsLabel.setText(_translate("Dialog", "Connected as:", None))
        self.connectionSettingsPushButton.setText(_translate("Dialog", "Connection Settings", None))
        self.projectLabel.setText(_translate("Dialog", "Project", None))
        self.deleteProjectPushButton.setText(_translate("Dialog", "Delete", None))
        self.newProjectPushButton.setText(_translate("Dialog", "New", None))
        self.deleteScenarioPushButton.setText(_translate("Dialog", "Delete", None))
        self.eventLabel.setText(_translate("Dialog", "Event", None))
        self.resultTypeLabel.setText(_translate("Dialog", "Result Type", None))
        self.scenarioLabel.setText(_translate("Dialog", "Scenario", None))
        self.uploadPushButton.setText(_translate("Dialog", "Upload", None))
        self.newEventPushButton.setText(_translate("Dialog", "New", None))
        self.newScenarioPushButton.setText(_translate("Dialog", "New", None))
        self.deleteEventPushButton.setText(_translate("Dialog", "Delete", None))
        self.browsePushButton.setText(_translate("Dialog", "Browse", None))
        self.fromFileRadioButton.setText(_translate("Dialog", "From file", None))
        self.label_4.setText(_translate("Dialog", "Resolution", None))
        self.resolutionSpinBox.setSuffix(_translate("Dialog", " m", None))
        self.fromCurrentRadioButton.setText(_translate("Dialog", "From current layer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Results", None))
        self.deleteOverlayPushButton.setText(_translate("Dialog", "Delete", None))
        self.newOverlayPushButton.setText(_translate("Dialog", "New", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Overlays", None))
        self.statusLabel.setText(_translate("Dialog", "statusLabel", None))

import resources_rc
