# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'upload_dialog_widget.ui'
#
# Created: Sun Jul 20 17:12:42 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(499, 343)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/illuvis/illuvis_u_32w.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setModal(True)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.resultTypeComboBox = QtGui.QComboBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultTypeComboBox.sizePolicy().hasHeightForWidth())
        self.resultTypeComboBox.setSizePolicy(sizePolicy)
        self.resultTypeComboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.resultTypeComboBox.setObjectName(_fromUtf8("resultTypeComboBox"))
        self.gridLayout.addWidget(self.resultTypeComboBox, 16, 1, 1, 1)
        self.projectComboBox = QtGui.QComboBox(Dialog)
        self.projectComboBox.setObjectName(_fromUtf8("projectComboBox"))
        self.gridLayout.addWidget(self.projectComboBox, 6, 1, 1, 2)
        self.scenarioComboBox = QtGui.QComboBox(Dialog)
        self.scenarioComboBox.setObjectName(_fromUtf8("scenarioComboBox"))
        self.gridLayout.addWidget(self.scenarioComboBox, 7, 1, 1, 2)
        self.uploadPushButton = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadPushButton.sizePolicy().hasHeightForWidth())
        self.uploadPushButton.setSizePolicy(sizePolicy)
        self.uploadPushButton.setObjectName(_fromUtf8("uploadPushButton"))
        self.gridLayout.addWidget(self.uploadPushButton, 16, 3, 1, 2)
        self.projectLabel = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectLabel.sizePolicy().hasHeightForWidth())
        self.projectLabel.setSizePolicy(sizePolicy)
        self.projectLabel.setObjectName(_fromUtf8("projectLabel"))
        self.gridLayout.addWidget(self.projectLabel, 6, 0, 1, 1)
        self.deleteProjectPushButton = QtGui.QPushButton(Dialog)
        self.deleteProjectPushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteProjectPushButton.sizePolicy().hasHeightForWidth())
        self.deleteProjectPushButton.setSizePolicy(sizePolicy)
        self.deleteProjectPushButton.setObjectName(_fromUtf8("deleteProjectPushButton"))
        self.gridLayout.addWidget(self.deleteProjectPushButton, 6, 3, 1, 1)
        self.newProjectPushButton = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newProjectPushButton.sizePolicy().hasHeightForWidth())
        self.newProjectPushButton.setSizePolicy(sizePolicy)
        self.newProjectPushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.newProjectPushButton.setObjectName(_fromUtf8("newProjectPushButton"))
        self.gridLayout.addWidget(self.newProjectPushButton, 6, 4, 1, 1)
        self.scenarioLabel = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scenarioLabel.sizePolicy().hasHeightForWidth())
        self.scenarioLabel.setSizePolicy(sizePolicy)
        self.scenarioLabel.setObjectName(_fromUtf8("scenarioLabel"))
        self.gridLayout.addWidget(self.scenarioLabel, 7, 0, 1, 1)
        self.deleteScenarioPushButton = QtGui.QPushButton(Dialog)
        self.deleteScenarioPushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteScenarioPushButton.sizePolicy().hasHeightForWidth())
        self.deleteScenarioPushButton.setSizePolicy(sizePolicy)
        self.deleteScenarioPushButton.setObjectName(_fromUtf8("deleteScenarioPushButton"))
        self.gridLayout.addWidget(self.deleteScenarioPushButton, 7, 3, 1, 1)
        self.newScenarioPushButton = QtGui.QPushButton(Dialog)
        self.newScenarioPushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newScenarioPushButton.sizePolicy().hasHeightForWidth())
        self.newScenarioPushButton.setSizePolicy(sizePolicy)
        self.newScenarioPushButton.setObjectName(_fromUtf8("newScenarioPushButton"))
        self.gridLayout.addWidget(self.newScenarioPushButton, 7, 4, 1, 1)
        self.eventLabel = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventLabel.sizePolicy().hasHeightForWidth())
        self.eventLabel.setSizePolicy(sizePolicy)
        self.eventLabel.setObjectName(_fromUtf8("eventLabel"))
        self.gridLayout.addWidget(self.eventLabel, 8, 0, 1, 1)
        self.deleteEventPushButton = QtGui.QPushButton(Dialog)
        self.deleteEventPushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteEventPushButton.sizePolicy().hasHeightForWidth())
        self.deleteEventPushButton.setSizePolicy(sizePolicy)
        self.deleteEventPushButton.setObjectName(_fromUtf8("deleteEventPushButton"))
        self.gridLayout.addWidget(self.deleteEventPushButton, 8, 3, 1, 1)
        self.newEventPushButton = QtGui.QPushButton(Dialog)
        self.newEventPushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newEventPushButton.sizePolicy().hasHeightForWidth())
        self.newEventPushButton.setSizePolicy(sizePolicy)
        self.newEventPushButton.setObjectName(_fromUtf8("newEventPushButton"))
        self.gridLayout.addWidget(self.newEventPushButton, 8, 4, 1, 1)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 11, 0, 1, 5)
        self.resultFileLabel = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultFileLabel.sizePolicy().hasHeightForWidth())
        self.resultFileLabel.setSizePolicy(sizePolicy)
        self.resultFileLabel.setObjectName(_fromUtf8("resultFileLabel"))
        self.gridLayout.addWidget(self.resultFileLabel, 15, 0, 1, 1)
        self.browsePushButton = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browsePushButton.sizePolicy().hasHeightForWidth())
        self.browsePushButton.setSizePolicy(sizePolicy)
        self.browsePushButton.setObjectName(_fromUtf8("browsePushButton"))
        self.gridLayout.addWidget(self.browsePushButton, 15, 3, 1, 2)
        self.resultTypeLabel = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultTypeLabel.sizePolicy().hasHeightForWidth())
        self.resultTypeLabel.setSizePolicy(sizePolicy)
        self.resultTypeLabel.setObjectName(_fromUtf8("resultTypeLabel"))
        self.gridLayout.addWidget(self.resultTypeLabel, 16, 0, 1, 1)
        self.eventComboBox = QtGui.QComboBox(Dialog)
        self.eventComboBox.setObjectName(_fromUtf8("eventComboBox"))
        self.gridLayout.addWidget(self.eventComboBox, 8, 1, 1, 2)
        self.resultFileLineEdit = QtGui.QLineEdit(Dialog)
        self.resultFileLineEdit.setObjectName(_fromUtf8("resultFileLineEdit"))
        self.gridLayout.addWidget(self.resultFileLineEdit, 15, 1, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 18, 3, 1, 2)
        self.connectedAsLabel = QtGui.QLabel(Dialog)
        self.connectedAsLabel.setObjectName(_fromUtf8("connectedAsLabel"))
        self.gridLayout.addWidget(self.connectedAsLabel, 2, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 4, 0, 1, 5)
        self.connectionSettingsPushButton = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectionSettingsPushButton.sizePolicy().hasHeightForWidth())
        self.connectionSettingsPushButton.setSizePolicy(sizePolicy)
        self.connectionSettingsPushButton.setObjectName(_fromUtf8("connectionSettingsPushButton"))
        self.gridLayout.addWidget(self.connectionSettingsPushButton, 3, 0, 1, 2)
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 16, 2, 1, 1)
        self.diskUseProgressBar = QtGui.QProgressBar(Dialog)
        self.diskUseProgressBar.setMinimum(0)
        self.diskUseProgressBar.setMaximum(500)
        self.diskUseProgressBar.setProperty("value", 0)
        self.diskUseProgressBar.setTextVisible(True)
        self.diskUseProgressBar.setObjectName(_fromUtf8("diskUseProgressBar"))
        self.gridLayout.addWidget(self.diskUseProgressBar, 17, 1, 1, 2)
        self.diskUsageLabel = QtGui.QLabel(Dialog)
        self.diskUsageLabel.setObjectName(_fromUtf8("diskUsageLabel"))
        self.gridLayout.addWidget(self.diskUsageLabel, 17, 0, 1, 1)
        self.iconLabel = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconLabel.sizePolicy().hasHeightForWidth())
        self.iconLabel.setSizePolicy(sizePolicy)
        self.iconLabel.setText(_fromUtf8(""))
        self.iconLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/illuvis/illuvis_logo_150w.png")))
        self.iconLabel.setScaledContents(False)
        self.iconLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.iconLabel.setObjectName(_fromUtf8("iconLabel"))
        self.gridLayout.addWidget(self.iconLabel, 1, 2, 3, 3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.statusLabel = QtGui.QLabel(Dialog)
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.gridLayout.addWidget(self.statusLabel, 18, 0, 1, 3)
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 13, 0, 1, 5)
        self.overlaysLabel = QtGui.QLabel(Dialog)
        self.overlaysLabel.setObjectName(_fromUtf8("overlaysLabel"))
        self.gridLayout.addWidget(self.overlaysLabel, 12, 0, 1, 1)
        self.overlayComboBox = QtGui.QComboBox(Dialog)
        self.overlayComboBox.setObjectName(_fromUtf8("overlayComboBox"))
        self.gridLayout.addWidget(self.overlayComboBox, 12, 1, 1, 2)
        self.deleteOverlayPushButton = QtGui.QPushButton(Dialog)
        self.deleteOverlayPushButton.setEnabled(False)
        self.deleteOverlayPushButton.setObjectName(_fromUtf8("deleteOverlayPushButton"))
        self.gridLayout.addWidget(self.deleteOverlayPushButton, 12, 3, 1, 1)
        self.newOverlayPushButton = QtGui.QPushButton(Dialog)
        self.newOverlayPushButton.setEnabled(False)
        self.newOverlayPushButton.setObjectName(_fromUtf8("newOverlayPushButton"))
        self.gridLayout.addWidget(self.newOverlayPushButton, 12, 4, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.uploadPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.accept)
        QtCore.QObject.connect(self.browsePushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.browseForFile)
        QtCore.QObject.connect(self.connectionSettingsPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.connectionSettingsButtonPressed)
        QtCore.QObject.connect(self.scenarioComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.refreshEvents)
        QtCore.QObject.connect(self.newProjectPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.newProjectPushButtonPressed)
        QtCore.QObject.connect(self.newScenarioPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.newScenarioPushButtonPressed)
        QtCore.QObject.connect(self.newEventPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.newEventPushButtonPressed)
        QtCore.QObject.connect(self.deleteProjectPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.deleteProjectPushButtonPressed)
        QtCore.QObject.connect(self.deleteScenarioPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.deleteScenarioPushButtonPressed)
        QtCore.QObject.connect(self.deleteEventPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.deleteEventPushButtonPressed)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("helpRequested()")), Dialog.helpPressed)
        QtCore.QObject.connect(self.newOverlayPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.newOverlayPushButtonPressed)
        QtCore.QObject.connect(self.projectComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.projectComboBoxChanged)
        QtCore.QObject.connect(self.deleteOverlayPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.deleteOverlayPushButtonPressed)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.connectionSettingsPushButton, self.projectComboBox)
        Dialog.setTabOrder(self.projectComboBox, self.deleteProjectPushButton)
        Dialog.setTabOrder(self.deleteProjectPushButton, self.newProjectPushButton)
        Dialog.setTabOrder(self.newProjectPushButton, self.scenarioComboBox)
        Dialog.setTabOrder(self.scenarioComboBox, self.deleteScenarioPushButton)
        Dialog.setTabOrder(self.deleteScenarioPushButton, self.newScenarioPushButton)
        Dialog.setTabOrder(self.newScenarioPushButton, self.eventComboBox)
        Dialog.setTabOrder(self.eventComboBox, self.deleteEventPushButton)
        Dialog.setTabOrder(self.deleteEventPushButton, self.newEventPushButton)
        Dialog.setTabOrder(self.newEventPushButton, self.resultFileLineEdit)
        Dialog.setTabOrder(self.resultFileLineEdit, self.browsePushButton)
        Dialog.setTabOrder(self.browsePushButton, self.resultTypeComboBox)
        Dialog.setTabOrder(self.resultTypeComboBox, self.uploadPushButton)
        Dialog.setTabOrder(self.uploadPushButton, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "illuvis Uploader", None))
        self.uploadPushButton.setText(_translate("Dialog", "Upload", None))
        self.projectLabel.setText(_translate("Dialog", "Project", None))
        self.deleteProjectPushButton.setText(_translate("Dialog", "Delete", None))
        self.newProjectPushButton.setText(_translate("Dialog", "New", None))
        self.scenarioLabel.setText(_translate("Dialog", "Scenario", None))
        self.deleteScenarioPushButton.setText(_translate("Dialog", "Delete", None))
        self.newScenarioPushButton.setText(_translate("Dialog", "New", None))
        self.eventLabel.setText(_translate("Dialog", "Event", None))
        self.deleteEventPushButton.setText(_translate("Dialog", "Delete", None))
        self.newEventPushButton.setText(_translate("Dialog", "New", None))
        self.resultFileLabel.setText(_translate("Dialog", "Result File", None))
        self.browsePushButton.setText(_translate("Dialog", "Browse", None))
        self.resultTypeLabel.setText(_translate("Dialog", "Result Type", None))
        self.connectedAsLabel.setText(_translate("Dialog", "Connected as:", None))
        self.connectionSettingsPushButton.setText(_translate("Dialog", "Connection Settings", None))
        self.diskUseProgressBar.setFormat(_translate("Dialog", "%v MB", None))
        self.diskUsageLabel.setText(_translate("Dialog", "Disk Usage", None))
        self.statusLabel.setText(_translate("Dialog", "statusLabel", None))
        self.overlaysLabel.setText(_translate("Dialog", "Overlays", None))
        self.deleteOverlayPushButton.setText(_translate("Dialog", "Delete", None))
        self.newOverlayPushButton.setText(_translate("Dialog", "New", None))

import resources_rc
